###
POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "randall2",
    "password": "123456"
}

###
GET http://localhost:8080/user/list
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJsb2dpbl91c2VyX2lkIjoyfQ.uTMGharDR3X_IT_dldSD6Zj2BYQdOJymwZuR2TH0hKQ


###
GET http://localhost:8080/user/list